spring.application.name=products
server.port=${PRODUCTS_PORT:5002}

jwt.secret=${JWT_SECRET:dev-secret}

storage.products.primary-file=${PRODUCTS_PRIMARY_STORAGE_FILE:data/products-primary.json}
storage.products.replica-file=${PRODUCTS_REPLICA_STORAGE_FILE:data/products-replica.json}
products.replica.name=${PRODUCTS_REPLICA_NAME:primary}
products.replica.port=${PRODUCTS_REPLICA_PORT:5012}
